# Generated by Django 5.2.5 on 2025-08-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('location', models.CharField(max_length=124, verbose_name='Local')),
                ('type', models.CharField(choices=[('estoque', 'Estoque'), ('cliente', 'Cliente'), ('tecnico', 'Técnico')], max_length=124, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('reason', models.CharField(max_length=124, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Motivo',
                'ordering': ['reason'],
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_trackings', to='controller_stock.location', verbose_name='Destino')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trackings', to='equipment.equipment', verbose_name='Equipamento')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origins_trackings', to='controller_stock.location', verbose_name='Origem')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trackings', to='controller_stock.reason', verbose_name='Motivo')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_changes', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Rastreio',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ControllerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='equipment.equipment', verbose_name='Equipamento')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_changes', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='controller_stock.location', verbose_name='Local')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controllers', to='controller_stock.reason', verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Estoque',
                'ordering': ['equipment'],
                'indexes': [models.Index(fields=['location'], name='controller__locatio_9017d1_idx')],
            },
        ),
    ]
