# Generated by Django 5.2.5 on 2025-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller_stock', '0004_alter_location_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controllerstock',
            options={'ordering': ['equipment'], 'verbose_name': 'Controle Estoque', 'verbose_name_plural': 'Controle Estoque'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rastreio'},
        ),
        migrations.AddField(
            model_name='tracking',
            name='observation',
            field=models.TextField(default='Estoque', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='controllerstock',
            name='observation',
            field=models.TextField(default='Estoque', verbose_name='Observação'),
        ),
    ]
