# Generated by Django 5.2.5 on 2025-08-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('branch', models.CharField(max_length=124, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['branch'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.CharField(max_length=124, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='StatusEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(max_length=72, unique=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status do equipamento',
                'verbose_name_plural': 'Status dos equipamentos',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='ModelEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('model', models.CharField(max_length=124, unique=True, verbose_name='Modelo')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='equipment.branch', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo do equipamento',
                'verbose_name_plural': 'Modelos dos equipamentos',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('mac_address', models.CharField(max_length=124, unique=True, verbose_name='Mac Address')),
                ('serial_number', models.CharField(max_length=124, unique=True, verbose_name='Serial Number')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.branch', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.category', verbose_name='Categoria')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_changes', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.modelequipment', verbose_name='Modelo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.statusequipment', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['model'],
            },
        ),
    ]
